INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO users(email, name, password, username, created_at) VALUES('admin@fakemail.com','Admin','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','admin', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user1@fakemail.com','User1','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user1', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user2@fakemail.com','User2','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user2', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user3@fakemail.com','User3','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user3', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user4@fakemail.com','User4','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user4', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user5@fakemail.com','User5','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user5', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user6@fakemail.com','User6','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user6', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user8@fakemail.com','User7','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user7', CURRENT_TIMESTAMP());
INSERT INTO users(email, name, password, username, created_at) VALUES('user7@fakemail.com','User8','$2a$10$bD.kXoZRQPhUvk.V0qy2aOtR74VYTx8/hoUWXkp.lHZgdkFdfAot2','user8', CURRENT_TIMESTAMP());
INSERT INTO user_roles(user_id, role_id) VALUES(1,1);
INSERT INTO user_roles(user_id, role_id) VALUES(2,2);
INSERT INTO user_roles(user_id, role_id) VALUES(3,2);
INSERT INTO user_roles(user_id, role_id) VALUES(4,2);
INSERT INTO user_roles(user_id, role_id) VALUES(5,2);
INSERT INTO user_roles(user_id, role_id) VALUES(6,2);
INSERT INTO user_roles(user_id, role_id) VALUES(7,2);
INSERT INTO user_roles(user_id, role_id) VALUES(8,2);
INSERT INTO user_roles(user_id, role_id) VALUES(9,2);
